source 'https://github.com/slb2709673/SlbSpces.git'
#use_frameworks!
use_modular_headers!

platform :ios, '8.0'

target 'slbswifttest_Example' do
  pod 'slbswifttest', :path => '../'

  target 'slbswifttest_Tests' do
    inherit! :search_paths

    
  end
end
